org: timbeccue
app: lesson-scheduler-flask
service: lesson-scheduler-backend

frameworkVersion: '3'

custom:
  wsgi:
    app: app.app

  pythonRequirements:
    # call `pip install` inside a container - useful for packages that have native dependencies (scipy et-al)
    dockerizePip: true

    # ignore dependencies because we need to pin the version of jinja, flask, markupsafe, and werkzeug, 
    # and for some reason flask and jinja are not compatible with their given versions.
    pipCmdExtraArgs:
      - --no-deps

    slim: true
    zip: true

provider:
  name: aws
  runtime: python3.9
  profile: personal

functions:
  api:
    handler: wsgi_handler.handler
    timeout: 20
    events:
      - httpApi: '*'

plugins:
  - serverless-wsgi
  - serverless-python-requirements
